# Normal Amulets
AMULET_ASSASSIN = 1201
AMULET_CAT = 1202
AMULET_BLUE = 1203
AMULET_CARCASS = 1204
AMULET_CARRIER = 1205
AMULET_CARRIER1 = 1206
AMULET_HUNTER = 1207
AMULET_INDOMITABLE = 1208
AMULET_WALL = 1209
AMULET_LEAPING = 1210
AMULET_LEAPING1 = 1211
AMULET_LIFE = 1212
AMULET_LIFE1 = 1213
AMULET_MURDER = 1214
AMULET_PATIENCE = 1215
AMULET_PUPPET = 1216
AMULET_RECHARGE = 1217
AMULET_FOX = 1218
AMULET_STRENGTH = 1219
AMULET_SWORD = 1220
AMULET_TECHNIQUE = 1221
AMULET_TRANSFORMATION = 1222
AMULET_VET = 1223

AMULET_ID_TO_NAME = {
    AMULET_ASSASSIN: "Assassin's Amulet",
    AMULET_CAT: "Black Cat's Amulet",
    AMULET_BLUE: "Blue Guardianship Amulet",
    AMULET_CARCASS: "Carcass Butcher's Amulet",
    AMULET_CARRIER: "Carrier's Amulet",
    AMULET_CARRIER1: "Carrier's Amulet +1",
    AMULET_HUNTER: "Hunter's Amulet",
    AMULET_INDOMITABLE: "Indomitable Amulet",
    AMULET_WALL: "Iron Wall Amulet",
    AMULET_LEAPING: "Leaping Amulet",
    AMULET_LEAPING1: "Leaping Amulet +1",
    AMULET_LIFE: "Life Amulet",
    AMULET_LIFE1: "Life Amulet +1",
    AMULET_MURDER: "Murderer Puppet's Amulet",
    AMULET_PATIENCE: "Patience Amulet",
    AMULET_PUPPET: "Puppet Destroyer's Amulet",
    AMULET_RECHARGE: "Recharged Amulet",
    AMULET_FOX: "Red Fox's Amulet",
    AMULET_STRENGTH: "Strength Amulet",
    AMULET_SWORD: "Swordsmanship Master's Amulet",
    AMULET_TECHNIQUE: "Technique Amulet",
    AMULET_TRANSFORMATION: "Transformation Amulet",
    AMULET_VET: "Veteran's Amulet"
}
ALL_AMULET = list(AMULET_ID_TO_NAME.keys())

# Boss Amulets
AMULET_GODARM = 1224
AMULET_AWAKENEDGOD = 1225
AMULET_CONQUERING = 1226
AMULET_DANCING = 1227
AMULET_EXTREMEMOD = 1228
AMULET_GHOSTWALK = 1229
AMULET_IMPREGNABLE = 1230
AMULET_NAMELESS = 1231
AMULET_HATRED = 1232
AMULET_TRIUMVIRATE = 1233

BOSS_AMULET_ID_TO_NAME = {
    AMULET_GODARM: "Arm of God Amulet",
    AMULET_AWAKENEDGOD: "Awakened God's Amulet",
    AMULET_CONQUERING: "Conquering Amulet",
    AMULET_DANCING: "Dancing One's Amulet",
    AMULET_EXTREMEMOD: "Extreme Modification Amulet",
    AMULET_GHOSTWALK: "Ghost Walk Amulet",
    AMULET_IMPREGNABLE: "Impregnable Fortress Amulet",
    AMULET_NAMELESS: "Nameless One's Amulet",
    AMULET_HATRED: "Piercing Hatred Amulet",
    AMULET_TRIUMVIRATE: "Triumvirate Amulet"
}
ALL_BOSS_AMULET = list(BOSS_AMULET_ID_TO_NAME.keys())

# NGP Amulets
AMULET_NGP1_BLUE = 1301
AMULET_NGP2_BLUE = 1302
AMULET_NGP1_HUNTER = 1303
AMULET_NGP1_INDOMITABLE = 1304
AMULET_NGP1_RECHARGED = 1305
AMULET_NGP1_STRENGTH = 1306
AMULET_NGP2_STRENGTH = 1307
AMULET_NGP1_TECHNIQUE = 1308
AMULET_NGP2_TECHNIQUE = 1309
AMULET_NGP1_TRANSFORMATION = 1310
AMULET_NGP2_TRANSFORMATION = 1311

NGP_AMULET_ID_TO_NAME = {
    AMULET_NGP1_BLUE: "Blue Guardianship Amulet +1",
    AMULET_NGP2_BLUE: "Blue Guardianship Amulet +2",
    AMULET_NGP1_HUNTER: "Hunter's Amulet +1",
    AMULET_NGP1_INDOMITABLE: "Indomitable Amulet +1",
    AMULET_NGP1_RECHARGED: "Recharged Amulet +1",
    AMULET_NGP1_STRENGTH: "Strength Amulet +1",
    AMULET_NGP2_STRENGTH: "Strength Amulet +2",
    AMULET_NGP1_TECHNIQUE: "Technique Amulet +1",
    AMULET_NGP2_TECHNIQUE: "Technique Amulet +2",
    AMULET_NGP1_TRANSFORMATION: "Transformation Amulet +1",
    AMULET_NGP2_TRANSFORMATION: "Transformation Amulet +2"
}
ALL_NGP_AMULET = list(NGP_AMULET_ID_TO_NAME.keys())

DLC_AMULET_COURAGE = 2405
DLC_AMULET_DUELIST = 2406
DLC_AMULET_FRENZIED = 2407
DLC_AMULET_GIANT = 2408
DLC_AMULET_LEGION = 2409
DLC_AMULET_PLUNDERING = 2410
DLC_AMULET_SHEPHERDS = 2411
DLC_AMULET_SOLUTION = 2412
DLC_AMULET_STRATEGIST = 2413
DLC_AMULET_STORYTELLER = 2414
DLC_AMULET_SURVIVAL = 2415
DLC_AMULET_TENACIOUS = 2416
DLC_AMULET_WHIRWIND = 2417
DLC_AMULET_SLEEP = 2418

DLC_AMULET_ID_TO_NAME = {
    DLC_AMULET_COURAGE: "Courage Amulet",
    DLC_AMULET_DUELIST: "Duelist's Amulet",
    DLC_AMULET_FRENZIED: "Frenzied Amulet",
    DLC_AMULET_GIANT: "Giant's Amulet",
    DLC_AMULET_LEGION: "Legion Amulet",
    DLC_AMULET_PLUNDERING: "Plundering Amulet",
    DLC_AMULET_SHEPHERDS: "Shepherd's Amulet",
    DLC_AMULET_SOLUTION: "Solutionist's Amulet ",
    DLC_AMULET_STRATEGIST: "Strategist's Amulet",
    DLC_AMULET_STORYTELLER: "Storyteller's Amulet",
    DLC_AMULET_SURVIVAL: "Survival Amulet",
    DLC_AMULET_TENACIOUS: "Tenacious Amulet",
    DLC_AMULET_WHIRWIND: "Whirlwind Amulet",
    DLC_AMULET_SLEEP: "Winter's Sleep Amulet"
}

ALL_DLC_AMULET = list(DLC_AMULET_ID_TO_NAME.keys())

DLC_BOSS_AMULET_MORBID = 2419
DLC_BOSS_AMULET_NIGHTMARE = 2420

DLC_BOSS_AMULET_ID_TO_NAME = {
    DLC_BOSS_AMULET_MORBID: "Morbid Ambition's Amulet",
    DLC_BOSS_AMULET_NIGHTMARE: "Nightmare's Amulet"
}

ALL_DLC_BOSS_AMULET = list(DLC_BOSS_AMULET_ID_TO_NAME.keys())
## TODO add dlc ngp amulets id's 2421-2430