# Recollections
RECOLLECTION_CURE = 1401
RECOLLECTION_MARK = 1402
RECOLLECTION_ARM = 1403
RECOLLECTION_BLOOD_RING = 1404
RECOLLECTION_APPLE = 1405
RECOLLECTION_BABY = 1406
RECOLLECTION_COMPLETED_DECODER = 1407
RECOLLECTION_DECODER = 1408
RECOLLECTION_WHISTLE = 1409
RECOLLECTION_GLOVE = 1410
RECOLLECTION_ERGO = 1411
RECOLLECTION_BATTERY = 1412
RECOLLECTION_MESSAGE = 1413
RECOLLECTION_SURPRISE1 = 1414
RECOLLECTION_BLEIWIES = 1415
RECOLLECTION_TOY = 1416
RECOLLECTION_PORTRAIT = 1417
RECOLLECTION_RED_LOCKET = 1418
RECOLLECTION_COP = 1419
RECOLLECTION_BRB = 1420
RECOLLECTION_NECKLACE = 1421
RECOLLECTION_WHITE_LOCKET = 1422
RECOLLECTION_COIN = 1423
RECOLLECTION_RING = 1424
RECOLLECTION_SURPRISE2 = 1425

RECOLLECTION_ID_TO_NAME = {
    RECOLLECTION_CURE: "A Cure for Antonia",
    RECOLLECTION_MARK: "Archbishop's Holy Mark",
    RECOLLECTION_ARM: "Arm of God",
    RECOLLECTION_BLOOD_RING: "Bloody Wedding Ring",
    RECOLLECTION_APPLE: "Bright Red Apple",
    RECOLLECTION_BABY: "Broken Baby Puppet",
    RECOLLECTION_COMPLETED_DECODER: "Completed Ergo Wavelength Decoder",
    RECOLLECTION_DECODER: "Ergo Wavelength Decoder",
    RECOLLECTION_WHISTLE: "Faded Whistle",
    RECOLLECTION_GLOVE: "Four-Fingered Glove",
    RECOLLECTION_ERGO: "Golden Ergo",
    RECOLLECTION_BATTERY: "Golden Lead-Acid Battery",
    RECOLLECTION_MESSAGE: "King of Puppets' Message",
    RECOLLECTION_SURPRISE1: "King of Riddles' Surprise Box (1)",
    RECOLLECTION_BLEIWIES: "La Bleiwies",
    RECOLLECTION_TOY: "Moon World Warrior Toy",
    RECOLLECTION_PORTRAIT: "Portrait of a Boy",
    RECOLLECTION_RED_LOCKET: "Red Actress's Locket",
    RECOLLECTION_COP: "Small Wooden Officer Puppet",
    RECOLLECTION_BRB: "Smiling Bunny Mark",
    RECOLLECTION_NECKLACE: "Someone's Necklace",
    RECOLLECTION_WHITE_LOCKET: "The White Lady's Locket",
    RECOLLECTION_COIN: "Venigni Commemorative Coin",
    RECOLLECTION_RING: "Wedding Ring",
    RECOLLECTION_SURPRISE2: "King of Riddles' Surprise Box (2)"
}

ALL_RECOLLECTION = list(RECOLLECTION_ID_TO_NAME.keys())

# Cryptic Vessels
CRYPTIC_ALIDORO = 1501
CRYPTIC_CRAFTED = 1502
CRYPTIC_JEWELED = 1503
CRYPTIC_MECHANICAL = 1504
CRYPTIC_OLD = 1505
CRYPTIC_RUSTY = 1506

CRYPTIC_ID_TO_NAME = {
    CRYPTIC_ALIDORO: "Alidoro's Cryptic Vessel",
    CRYPTIC_CRAFTED: "Crafted Cryptic Vessel",
    CRYPTIC_JEWELED: "Jeweled Cryptic Vessel",
    CRYPTIC_MECHANICAL: "Mechanical Cryptic Vessel",
    CRYPTIC_OLD: "Old Cryptic Vessel",
    CRYPTIC_RUSTY: "Rusty Cryptic Vessel"
}

ALL_CRYPTIC = list(CRYPTIC_ID_TO_NAME.keys())

# DeCrypt Vessels
DECRYPT_ALIDORO = 1507
DECRYPT_CRAFTED = 1508
DECRYPT_JEWELED = 1509
DECRYPT_MECHANICAL = 1510
DECRYPT_OLD = 1511
DECRYPT_RUSTY = 1512

DECRYPT_ID_TO_NAME = {
    DECRYPT_ALIDORO: "Alidoro's Cryptic Vessel Decryption",
    DECRYPT_CRAFTED: "Crafted Cryptic Vessel Decryption",
    DECRYPT_JEWELED: "Jeweled Cryptic Vessel Decryption",
    DECRYPT_MECHANICAL: "Mechanical Cryptic Vessel Decryption",
    DECRYPT_OLD: "Old Cryptic Vessel Decryption",
    DECRYPT_RUSTY: "Rusty Cryptic Vessel Decryption"
}

ALL_DECRYPT = list(DECRYPT_ID_TO_NAME.keys())

# Records
RECORD_DIVINE = 1601
RECORD_PRINCESS = 1602
RECORD_FASCINATION = 1603
RECORD_FEEL = 1604
RECORD_MEMORY = 1605
RECORD_MISTY = 1606
RECORD_PROPOSAL = 1607
RECORD_QUIXOTIC = 1608
RECORD_SHADOW = 1609
RECORD_SOMEDAY = 1610
RECORD_WHY = 1611

RECORD_ID_TO_NAME = {
    RECORD_DIVINE: "Divine Service",
    RECORD_PRINCESS: "Far East Princess",
    RECORD_FASCINATION: "Fascination",
    RECORD_FEEL: "Feel",
    RECORD_MEMORY: "Memory Of Beach",
    RECORD_MISTY: "Misty E'rA",
    RECORD_PROPOSAL: "Proposal, Flower, Wolf Part 1",
    RECORD_QUIXOTIC: "Quixotic",
    RECORD_SHADOW: "Shadow Flower",
    RECORD_SOMEDAY: "Someday",
    RECORD_WHY: "Why"
}

ALL_RECORDS = list(RECORD_ID_TO_NAME.keys())

# Books
COLLECTABLE_ARCHBISHOP = 1701
COLLECTABLE_BRB = 1702
COLLECTABLE_DESCARTES = 1703
COLLECTABLE_3BROS = 1704
COLLECTABLE_CAMILE = 1705
COLLECTABLE_FRAYED = 1706
COLLECTABLE_GULLAIME = 1707
COLLECTABLE_MOONLIGHT = 1708
COLLECTABLE_EXPERIMENT = 1709
COLLECTABLE_TECHNICIANS = 1710
COLLECTABLE_GUIDE3 = 1711
COLLECTABLE_INCIDENT = 1712
COLLECTABLE_SCANDAL = 1713
COLLECTABLE_SENTRY = 1714
COLLECTABLE_CONFESSION = 1715
COLLECTABLE_PISTRIS = 1716
COLLECTABLE_PISTRIS2 = 1717
COLLECTABLE_PISTRIS3 = 1718
COLLECTABLE_SOME_REPORT = 1719
COLLECTABLE_SPECIAL_REPORT = 1720
COLLECTABLE_GUIDE = 1721
COLLECTABLE_GUIDE2 = 1722
COLLECTABLE_GUIDE4 = 1723
# Letters
COLLECTABLE_BLOODY = 1724
COLLECTABLE_BUNDLE = 1725
COLLECTABLE_CECILE = 1726
COLLECTABLE_CHERRY = 1727
COLLECTABLE_FROZEN = 1728
COLLECTABLE_HINT = 1729
COLLECTABLE_AHEAD = 1730
COLLECTABLE_LOVER = 1731
COLLECTABLE_COUNTER = 1732
COLLECTABLE_BUTTERFLY = 1733
COLLECTABLE_ETERNAL = 1734
COLLECTABLE_ATKINSON = 1735
COLLECTABLE_GEPETTO = 1736
# Newspapers
COLLECTABLE_ECCENTRIC = 1737
COLLECTABLE_183 = 1738
COLLECTABLE_1124 = 1739
COLLECTABLE_CHAMPION = 1740
COLLECTABLE_MASKS = 1741
# Notes
COLLECTABLE_ARTISTS = 1742
COLLECTABLE_BAPTISTS = 1743
COLLECTABLE_DOCTOR = 1744
COLLECTABLE_TEST = 1745
COLLECTABLE_MANAGER = 1746
COLLECTABLE_KROUD = 1747
COLLECTABLE_PASSENGER = 1748
COLLECTABLE_SLUM = 1749
COLLECTABLE_ARCHIVES = 1750
COLLECTABLE_CHOIR = 1751
COLLECTABLE_TORN = 1752
COLLECTABLE_VENIGNI = 1753
COLLECTABLE_PRAYER = 1754
# pictures
COLLECTABLE_BLEIWIES = 1755
COLLECTABLE_PARADE = 1756
COLLECTABLE_MIRACLE = 1757
COLLECTABLE_CONCERT = 1758
COLLECTABLE_CHARITYHOUSE = 1759
COLLECTABLE_SHOW = 1760
COLLECTABLE_DOGFISH = 1761
COLLECTABLE_WITCH = 1762
COLLECTABLE_WANTED = 1763
COLLECTABLE_ALIDORO = 1764

COLLECTABLE_ID_TO_NAME = {
    # Books
    COLLECTABLE_ARCHBISHOP: "Archbishop's Diary",
    COLLECTABLE_BRB: "Black Rabbit Brotherhood Ledger",
    COLLECTABLE_DESCARTES: "Descartes's Note",
    COLLECTABLE_3BROS: "Fairytale Of The Three Brothers Of The Workshop Tower",
    COLLECTABLE_CAMILE: "First Discovery, Camille",
    COLLECTABLE_FRAYED: "Frayed Notebook",
    COLLECTABLE_GULLAIME: "Guillaume's Ballad",
    COLLECTABLE_MOONLIGHT: "Moonlight Town Guide",
    COLLECTABLE_EXPERIMENT: "Notes From An Experiment",
    COLLECTABLE_TECHNICIANS: "Primer For Workshop Technicians",
    COLLECTABLE_GUIDE3: "Ripped Venigni's Krat Landmark Guide III",
    COLLECTABLE_INCIDENT: "Rose Estate Incident, Left As A Mystery",
    COLLECTABLE_SCANDAL: "Scandal! V, The Tragedy Behind The Flamboyance",
    COLLECTABLE_SENTRY: "Sentry's Notebook",
    COLLECTABLE_CONFESSION: "Simon Manus's Confession",
    COLLECTABLE_PISTRIS: "So Said Pistris I",
    COLLECTABLE_PISTRIS2: "So Said Pistris II",
    COLLECTABLE_PISTRIS3: "So Said Pistris III",
    COLLECTABLE_SOME_REPORT: "Someone's Report Notes Notebook",
    COLLECTABLE_SPECIAL_REPORT: "Special Report! Foreigner's Confession",
    COLLECTABLE_GUIDE: "Venigni's Krat Landmark Guide I",
    COLLECTABLE_GUIDE2: "Venigni's Krat Landmark Guide II",
    COLLECTABLE_GUIDE4: "Venigni's Krat Landmark Guide IV",
    # letters
    COLLECTABLE_BLOODY: "Bloody Letter",
    COLLECTABLE_BUNDLE: "Bundle Of Old Letters",
    COLLECTABLE_CECILE: "Cecile's Written Confession",
    COLLECTABLE_CHERRY: "Cherry-Scented Letter",
    COLLECTABLE_FROZEN: "Frozen Man's Letter",
    COLLECTABLE_HINT: "King of Riddles' Hint",
    COLLECTABLE_AHEAD: "Letter From Someone Who Has Gone Ahead",
    COLLECTABLE_LOVER: "Lover's Letter",
    COLLECTABLE_COUNTER: "Note Left at the Counter",
    COLLECTABLE_BUTTERFLY: "The Blue Butterfly's Letter",
    COLLECTABLE_ETERNAL: "The Letter of the Eternal",
    COLLECTABLE_ATKINSON: "Atkinson's Letter",
    COLLECTABLE_GEPETTO: "Geppetto's Letter",
    # Newspapers
    COLLECTABLE_ECCENTRIC: "Have You Seen This Eccentric?!",
    COLLECTABLE_183: "Krat Times Issue 183",
    COLLECTABLE_1124: "Krat News Issue 1124",
    COLLECTABLE_CHAMPION: "Resurrection! Champion Victor Has Returned!",
    COLLECTABLE_MASKS: "This Month's Trend: Stalker Masks",
    # Notes
    COLLECTABLE_ARTISTS: "Artist's Doodle",
    COLLECTABLE_BAPTISTS: "Crumpled Baptist's Doodle",
    COLLECTABLE_DOCTOR: "Doctor's Confession",
    COLLECTABLE_TEST: "Experiment Report of Order - Test Subject 890",
    COLLECTABLE_MANAGER: "Factory Manager's Report",
    COLLECTABLE_KROUD: "Order of Kroud Report",
    COLLECTABLE_PASSENGER: "Passenger's Note",
    COLLECTABLE_SLUM: "Scribbles Of Slum Resident",
    COLLECTABLE_ARCHIVES: "Sweepers Branch Office Newspaper Archives",
    COLLECTABLE_CHOIR: "Stained Choir Sheet Music",
    COLLECTABLE_TORN: "Torn Doodle",
    COLLECTABLE_VENIGNI: "Venigni's Guide",
    COLLECTABLE_PRAYER: "Woman's Prayer",
    # pictures
    COLLECTABLE_BLEIWIES: "Have A Taste Of La Bleiwies, The Greatest Wine In The World",
    COLLECTABLE_PARADE: "Introducing The Parade Puppet!",
    COLLECTABLE_MIRACLE: "Miracle Cure",
    COLLECTABLE_CONCERT: "Monad Charity House Concert",
    COLLECTABLE_CHARITYHOUSE: "Monad Charity House Guide",
    COLLECTABLE_SHOW: "The Greatest Show On Earth Is Coming!",
    COLLECTABLE_DOGFISH: "The Great Venigni And Pistris The Submarine",
    COLLECTABLE_WITCH: "The Witch's Tower And Princess Poster",
    COLLECTABLE_WANTED: "Wanted: Black Rabbit Brotherhood",
    COLLECTABLE_ALIDORO: "Wanted: Alidoro"
}

ALL_COLLECTABLE = list(COLLECTABLE_ID_TO_NAME.keys())

DLC_RECOLLECTION_SEED = 2431
DLC_RECOLLECTION_COIN = 2432
DLC_RECOLLECTION_SHOES = 2433
DLC_RECOLLECTION_CANVAS = 2434
DLC_RECOLLECTION_HORN = 2435
DLC_RECOLLECTION_ART = 2436
DLC_RECOLLECTION_PILL = 2437
DLC_RECOLLECTION_BEER = 2438
DLC_RECOLLECTION_PAINT = 2439
DLC_RECOLLECTION_COLLAR = 2440
DLC_RECOLLECTION_DISK = 2441
DLC_RECOLLECTION_BROADBAY = 2442
DLC_RECOLLECTION_WATCH = 2443
DLC_RECOLLECTION_TEA = 2444

DLC_RECOLLECTION_ID_TO_NAME = {
    DLC_RECOLLECTION_SEED: "Golden Seed",
    DLC_RECOLLECTION_COIN: "Carnival Coin",
    DLC_RECOLLECTION_SHOES: "Rose Shoes",
    DLC_RECOLLECTION_CANVAS: "Blank Canvas",
    DLC_RECOLLECTION_HORN: "Daylight-Wreathed Horn",
    DLC_RECOLLECTION_ART: "Goddard's Art Supplies",
    DLC_RECOLLECTION_PILL: "Empty Painkiller Bottle",
    DLC_RECOLLECTION_BEER: "Old Bottle of Beer",
    DLC_RECOLLECTION_PAINT: "Painter's Sky",
    DLC_RECOLLECTION_COLLAR: "Bell Collar",
    DLC_RECOLLECTION_DISK: "Ancient Disk",
    DLC_RECOLLECTION_BROADBAY: "Broadbay 30 Year",
    DLC_RECOLLECTION_WATCH: "Genius Meister's Pocket Watch",
    DLC_RECOLLECTION_TEA: "Royal Flower Tea Set"
}

ALL_DLC_RECOLLECTION = list(DLC_RECOLLECTION_ID_TO_NAME.keys())

DLC_CRYPTIC_BLOODY = 2445
DLC_CRYPTIC_CORRODED = 2446
DLC_CRYPTIC_FROSTED = 2447

DLC_CRYPTIC_ID_TO_NAME = {
    DLC_CRYPTIC_BLOODY: "Bloody Cipher Machine",
    DLC_CRYPTIC_CORRODED: "Corroded Cipher Machine",
    DLC_CRYPTIC_FROSTED: "Frosted Cipher Machine"
}

ALL_DLC_CRYPTIC = list(DLC_CRYPTIC_ID_TO_NAME.keys())