OUTFIT_ALCHEMIST = 401
OUTFIT_BLACK_CAT = 402
OUTFIT_BLUE_BLOOD = 403
OUTFIT_MAD_DONKEY = 404
OUTFIT_OWL_DOCTOR = 405
OUTFIT_PUPPET_PRINCE = 406
OUTFIT_RED_FOX = 407
OUTFIT_ROBBER = 408
OUTFIT_MEMORY = 409
OUTFIT_SURVIVOR_HUNT = 410
OUTFIT_ATONED_HUNT = 411
OUTFIT_MONSTER_SWEEPER = 412
OUTFIT_WHITE_LADY = 413
OUTFIT_WORKSHOP = 414
OUTFIT_MISCHIEVOUS = 415
OUTFIT_SIGNATURE = 416
OUTFIT_TREASURE = 434
OUTFIT_HONORABLE = 435

# outfits
OUTFIT_ID_TO_NAME = {
    OUTFIT_ALCHEMIST: "Alchemist's Cape",
    OUTFIT_BLACK_CAT: "Black Cat's Hunting Apparel",
    OUTFIT_BLUE_BLOOD: "Blue Blood's Tailcoat",
    OUTFIT_MAD_DONKEY: "Mad Donkey's Hunting Apparel",
    OUTFIT_OWL_DOCTOR: "Owl Doctor's Hunting Apparel",
    OUTFIT_PUPPET_PRINCE: "Puppet Prince's Formal Dress",
    OUTFIT_RED_FOX: "Red Fox's Hunting Apparel",
    OUTFIT_ROBBER: "Robber Weasel's Hunting Apparel",
    OUTFIT_MEMORY: "Someone's Memory",
    OUTFIT_SURVIVOR_HUNT: "Survivor's Hunting Apparel",
    OUTFIT_ATONED_HUNT: "The Atoned's Hunting Apparel",
    OUTFIT_MONSTER_SWEEPER: "Monster Sweeper's Hunting Apparel",
    OUTFIT_WHITE_LADY: "White Lady's Hunting Clothes",
    OUTFIT_WORKSHOP: "Workshop Master's Workwear",
    OUTFIT_MISCHIEVOUS: "Mischievous Puppet's Clothes",
    OUTFIT_SIGNATURE: "The Great Venigni's Signature Coat",
    OUTFIT_TREASURE: "Treasure Hunter's Hunting Apparel",
    OUTFIT_HONORABLE: "Armor of The Honorable"
}
ALL_OUTFITS = list(OUTFIT_ID_TO_NAME.keys())

# Accessories
ACCESSORY_BLACK_CAT = 417
ACCESSORY_MAD_DONKEY = 418
ACCESSORY_OWL_DOCTOR = 419
ACCESSORY_RED_FOX = 420
ACCESSORY_ROBBER = 421
ACCESSORY_SURVIVOR = 422
ACCESSORY_ATONED = 423
ACCESSORY_MISCHIEVOUS = 424
ACCESSORY_VENIGNI_GLASS = 425
ACCESSORY_PARADE = 426
ACCESSORY_ALCHEMIST = 427
ACCESSORY_EMERALD_GLASS = 428
ACCESSORY_WHITE_LADY = 429
ACCESSORY_WINTER = 430
ACCESSORY_RED_NOSE = 431
ACCESSORY_TREASURE = 432
ACCESSORY_ANTLERS = 433
ACCESSORY_HONORABLE = 436

ACCESSORY_ID_TO_NAME = {
    ACCESSORY_BLACK_CAT: "Black Cat's Mask",
    ACCESSORY_MAD_DONKEY: "Mad Donkey's Mask",
    ACCESSORY_OWL_DOCTOR: "Owl Doctor's Mask",
    ACCESSORY_RED_FOX: "Red Fox's Mask",
    ACCESSORY_ROBBER: "Robber Weasel's Mask",
    ACCESSORY_SURVIVOR: "Survivor's Mask",
    ACCESSORY_ATONED: "The Atoned's Mask",
    ACCESSORY_MISCHIEVOUS: "Mischievous Puppet's Parade Hat",
    ACCESSORY_VENIGNI_GLASS: "The Great Venigni's Glasses",
    ACCESSORY_PARADE: "Mask worn by those preparing for the festival",
    ACCESSORY_ALCHEMIST: "Alchemist's Hat",
    ACCESSORY_EMERALD_GLASS: "Illusory Emerald Glasses",
    ACCESSORY_WHITE_LADY: "The White Lady's Mask",
    ACCESSORY_WINTER: "Winter Festival Peaked Hat",
    ACCESSORY_RED_NOSE: "Midwinter Night's Red Nose",
    ACCESSORY_TREASURE: "Treasure Hunter's Mask",
    ACCESSORY_ANTLERS: "Earnest Reindeer's Antlers",
    ACCESSORY_HONORABLE: "Bandana of the Honorable"
}
ALL_ACCESSORY = list(ACCESSORY_ID_TO_NAME.keys())

DLC_OUTFIT_BLUE_SHEEP = 2029
DLC_OUTFIT_DETECTIVE = 2030
DLC_OUTFIT_SNAIL = 2031
DLC_OUTFIT_LEADER = 2032
DLC_OUTFIT_RED = 2035
DLC_OUTFIT_WINTER = 2036

DLC_OUTFIT_ID_TO_NAME = {
    DLC_OUTFIT_BLUE_SHEEP: "Blue Sheep's Battle Apparel",
    DLC_OUTFIT_DETECTIVE: "Famed Detective's Coat",
    DLC_OUTFIT_SNAIL: "Golden Snail's Tailcoat",
    DLC_OUTFIT_LEADER: "Leader's Battle Apparel",
    DLC_OUTFIT_RED: "Reddened Tailcoat",
    DLC_OUTFIT_WINTER: "Winter's Hunting Apparel"
}

ALL_DLC_OUTFITS = list(DLC_OUTFIT_ID_TO_NAME.keys())

DLC_ACCESSORY_SHEEP = 2037
DLC_ACCESSORY_HAT = 2038
DLC_ACCESSORY_MUSTACHE = 2039
DLC_ACCESSORY_MONOCLE = 2040
DLC_ACCESSORY_SNAIL = 2041
DLC_ACCESSORY_ADVENTURE = 2042
DLC_ACCESSORY_LEADER = 2043
DLC_ACCESSORY_CROWN = 2044
DLC_ACCESSORY_MANIAC = 2045
DLC_ACCESSORY_ECCENTRIC = 2046
DLC_ACCESSORY_ELDEST = 2047
DLC_ACCESSORY_YOUNGEST = 2048
DLC_ACCESSORY_EYEPATCH = 2049
DLC_ACCESSORY_WINTER = 2050

DLC_ACCESSORY_ID_TO_NAME = {
    DLC_ACCESSORY_SHEEP: "Blue Sheep's Mask",
    DLC_ACCESSORY_HAT: "Famed Detective's Hat",
    DLC_ACCESSORY_MUSTACHE: "Famous Detective's Mustache",
    DLC_ACCESSORY_MONOCLE: "Genius Meister's Monocle",
    DLC_ACCESSORY_SNAIL: "Golden Snail's Mask",
    DLC_ACCESSORY_ADVENTURE: "Great Adventure Mask",
    DLC_ACCESSORY_LEADER: "Leader's Mask",
    DLC_ACCESSORY_CROWN: "Puppet Prince's Imperial Crown",
    DLC_ACCESSORY_MANIAC: "The Battle Maniac's Mask",
    DLC_ACCESSORY_ECCENTRIC: "The Eccentric's Mask",
    DLC_ACCESSORY_ELDEST: "The Eldest's Gas Mask",
    DLC_ACCESSORY_YOUNGEST: "The Youngest's Mask",
    DLC_ACCESSORY_EYEPATCH: "Veteran's Eyepatch",
    DLC_ACCESSORY_WINTER: "Winter's Hunting Hat"
}

ALL_DLC_ACCESSORY = list(DLC_ACCESSORY_ID_TO_NAME.keys())

DLC_OUTFIT_BLACK_DEATHS = 2027
DLC_OUTFIT_BLAZING_DEATHS = 2028
DLC_OUTFIT_PREMEATING_DEATHS = 2033
DLC_OUTFIT_PIERCING_DEATHS = 2034

BRB_OUTFIT_ID_TO_NAME = {
    DLC_OUTFIT_BLACK_DEATHS: "Black Death's Protective Apparel",
    DLC_OUTFIT_BLAZING_DEATHS: "Blazing Death's Hunting Apparel",
    DLC_OUTFIT_PREMEATING_DEATHS: "Permeating Death's Hunting Apparel",
    DLC_OUTFIT_PIERCING_DEATHS: "Piercing Death's Hunting Apparel"
}

ALL_BRB_OUTFIT = list(BRB_OUTFIT_ID_TO_NAME.keys())