# Frames
PARTS_BASIC_FRAME = 1001
PARTS_LIGHT_FRAME = 1002
PARTS_STRENGTHENING_FRAME = 1003
PARTS_HEAVY_FRAME = 1004
PARTS_EXTERAHEAVY_FRAME = 1005
PARTS_150_FRAME = 1006
PARTS_250_FRAME = 1007
PARTS_350_FRAME = 1008

# Cartridges
PARTS_BREAK1_CART = 1009
PARTS_DISRUPTION1_CART = 1010
PARTS_SHOCK1_CART = 1011
PARTS_BREAK2_CART = 1012
PARTS_DISRUPTION2_CART = 1013
PARTS_SHOCK2_CART = 1014
PARTS_BREAK3_CART = 1015
PARTS_DISRUPTION3_CART = 1016
PARTS_SHOCK3_CART = 1017

# Converters
PARTS_BASIC_CART = 1018
PARTS_BASIC_CONV = 1019
PARTS_CORROSION1_CONV = 1020
PARTS_INSULATION1_CONV = 1021
PARTS_RADIATION1_CONV = 1022
PARTS_CORROSION2_CONV = 1023
PARTS_INSULATION2_CONV = 1024
PARTS_RADIATION2_CONV = 1025
PARTS_CORROSION3_CONV = 1026
PARTS_INSULATION3_CONV = 1027
PARTS_RADIATION3_CONV = 1028

# Liners
PARTS_BASIC_LINER = 1029
PARTS_SLASH1_LINER = 1030
PARTS_PIERCE1_LINER = 1031
PARTS_STRIKE1_LINER = 1032
PARTS_SLASH2_LINER = 1033
PARTS_PIERCE2_LINER = 1034
PARTS_STRIKE2_LINER = 1035
PARTS_SLASH3_LINER = 1036
PARTS_PIERCE3_LINER = 1037
PARTS_STRIKE3_LINER = 1038
PARTS_SLASH4_LINER = 1039
PARTS_PIERCE4_LINER = 1040
PARTS_STRIKE4_LINER = 1041

PARTS_ID_TO_NAME = {
    PARTS_BASIC_FRAME: "Workshop Union Basic Frame",
    PARTS_LIGHT_FRAME: "Workshop Union Lightweight Frame",
    PARTS_STRENGTHENING_FRAME: "Workshop Union Strengthening Frame",
    PARTS_HEAVY_FRAME: "Arch Heavyweight Frame",
    PARTS_EXTERAHEAVY_FRAME: "Arch Extra Heavyweight Frame",
    PARTS_150_FRAME: "LADA F150 Frame",
    PARTS_250_FRAME: "LADA F250 Frame",
    PARTS_350_FRAME: "LADA F350 Frame",
    PARTS_BREAK1_CART: "Belford Break Cartridge",
    PARTS_DISRUPTION1_CART: "Belford Disruption Cartridge",
    PARTS_SHOCK1_CART: "Belford Shock Cartridge",
    PARTS_BREAK2_CART: "Arch Break Cartridge",
    PARTS_DISRUPTION2_CART: "Arch Disruption Cartridge",
    PARTS_SHOCK2_CART: "Arch Shock Cartridge",
    PARTS_BREAK3_CART: "LADA Break Cartridge",
    PARTS_DISRUPTION3_CART: "LADA Disruption Cartridge",
    PARTS_SHOCK3_CART: "LADA Shock Cartridge",
    PARTS_BASIC_CART: "Workshop Union Cartridge Prototype",
    PARTS_BASIC_CONV: "Workshop Union Old Generation Converter",
    PARTS_CORROSION1_CONV: "Workshop Union Standard Corrosion Resistance Converter",
    PARTS_INSULATION1_CONV: "Workshop Union Standard Insulation Converter",
    PARTS_RADIATION1_CONV: "Workshop Union Standard Radiation Converter",
    PARTS_CORROSION2_CONV: "Belford Superior Corrosion Resistance Converter",
    PARTS_INSULATION2_CONV: "Belford Superior Insulation Converter",
    PARTS_RADIATION2_CONV: "Belford Superior Radiation Converter",
    PARTS_CORROSION3_CONV: "LADA Large Capacity Corrosion Resistance Converter",
    PARTS_INSULATION3_CONV: "LADA Large Capacity Insulation Converter",
    PARTS_RADIATION3_CONV: "LADA Large Capacity Radiation Converter",
    PARTS_BASIC_LINER: "Workshop Union Certified Liner",
    PARTS_SLASH1_LINER: "Workshop Union Fiber-Reinforced Liner",
    PARTS_PIERCE1_LINER: "Workshop Union Multi-Layer Liner",
    PARTS_STRIKE1_LINER: "Workshop Union Spaced Armor Liner",
    PARTS_SLASH2_LINER: "Belford Fiber-Reinforced Liner",
    PARTS_PIERCE2_LINER: "Belford Multi-Layer Liner",
    PARTS_STRIKE2_LINER: "Belford Spaced Armor Liner",
    PARTS_SLASH3_LINER: "Arch Fiber-Reinforced Liner",
    PARTS_PIERCE3_LINER: "Arch Multi-Layer Liner",
    PARTS_STRIKE3_LINER: "Arch Spaced Armor Liner",
    PARTS_SLASH4_LINER: "LADA Fiber-Reinforced Liner",
    PARTS_PIERCE4_LINER: "LADA Multi-Layer Liner",
    PARTS_STRIKE4_LINER: "LADA Spaced Armor Liner"
}
ALL_PARTS_MATERIALS = list(PARTS_ID_TO_NAME.keys())

# Frames
PARTS_NGP1_LIGHT_FRAME = 1101
PARTS_NGP1_STRENGTHENING_FRAME = 1102
PARTS_NGP1_HEAVY_FRAME = 1103
PARTS_NGP1_EXTERAHEAVY_FRAME = 1104
PARTS_NGP1_150_FRAME = 1105
PARTS_NGP1_250_FRAME = 1106
PARTS_NGP1_350_FRAME = 1107
PARTS_NGP2_LIGHT_FRAME = 1108
PARTS_NGP2_STRENGTHENING_FRAME = 1109
PARTS_NGP2_HEAVY_FRAME = 1110
PARTS_NGP2_EXTERAHEAVY_FRAME = 1111
PARTS_NGP2_150_FRAME = 1112
PARTS_NGP2_250_FRAME = 1113
PARTS_NGP2_350_FRAME = 1114
# Cartridges
PARTS_NGP1_BREAK1_CART = 1115
PARTS_NGP1_DISRUPTION1_CART = 1116
PARTS_NGP1_SHOCK1_CART = 1117
PARTS_NGP1_BREAK2_CART = 1118
PARTS_NGP1_DISRUPTION2_CART = 1119
PARTS_NGP1_SHOCK2_CART = 1120
PARTS_NGP1_BREAK3_CART = 1121
PARTS_NGP1_DISRUPTION3_CART = 1122
PARTS_NGP1_SHOCK3_CART = 1123
PARTS_NGP2_BREAK1_CART = 1124
PARTS_NGP2_DISRUPTION1_CART = 1125
PARTS_NGP2_SHOCK1_CART = 1126
PARTS_NGP2_BREAK2_CART = 1127
PARTS_NGP2_DISRUPTION2_CART = 1128
PARTS_NGP2_SHOCK2_CART = 1129
PARTS_NGP2_BREAK3_CART = 1130
PARTS_NGP2_DISRUPTION3_CART = 1131
PARTS_NGP2_SHOCK3_CART = 1132
# converters
PARTS_NGP1_CORROSION1_CONV = 1133
PARTS_NGP1_INSULATION1_CONV = 1134
PARTS_NGP1_RADIATION1_CONV = 1135
PARTS_NGP1_CORROSION2_CONV = 1136
PARTS_NGP1_INSULATION2_CONV = 1137
PARTS_NGP1_RADIATION2_CONV = 1138
PARTS_NGP1_CORROSION3_CONV = 1139
PARTS_NGP1_INSULATION3_CONV = 1140
PARTS_NGP1_RADIATION3_CONV = 1141
PARTS_NGP2_CORROSION1_CONV = 1142
PARTS_NGP2_INSULATION1_CONV = 1143
PARTS_NGP2_RADIATION1_CONV = 1144
PARTS_NGP2_CORROSION2_CONV = 1145
PARTS_NGP2_INSULATION2_CONV = 1146
PARTS_NGP2_RADIATION2_CONV = 1147
PARTS_NGP2_CORROSION3_CONV = 1148
PARTS_NGP2_INSULATION3_CONV = 1149
PARTS_NGP2_RADIATION3_CONV = 1150
# liners
PARTS_NGP1_SLASH1_LINER = 1151
PARTS_NGP1_PIERCE1_LINER = 1152
PARTS_NGP1_STRIKE1_LINER = 1153
PARTS_NGP1_SLASH2_LINER = 1154
PARTS_NGP1_PIERCE2_LINER = 1155
PARTS_NGP1_STRIKE2_LINER = 1156
PARTS_NGP1_SLASH3_LINER = 1157
PARTS_NGP1_PIERCE3_LINER = 1158
PARTS_NGP1_STRIKE3_LINER = 1159
PARTS_NGP1_SLASH4_LINER = 1160
PARTS_NGP1_PIERCE4_LINER = 1161
PARTS_NGP1_STRIKE4_LINER = 1162
PARTS_NGP2_SLASH1_LINER = 1163
PARTS_NGP2_PIERCE1_LINER = 1164
PARTS_NGP2_STRIKE1_LINER = 1165
PARTS_NGP2_SLASH2_LINER = 1166
PARTS_NGP2_PIERCE2_LINER = 1167
PARTS_NGP2_STRIKE2_LINER = 1168
PARTS_NGP2_SLASH3_LINER = 1169
PARTS_NGP2_PIERCE3_LINER = 1170
PARTS_NGP2_STRIKE3_LINER = 1171
PARTS_NGP2_SLASH4_LINER = 1172
PARTS_NGP2_PIERCE4_LINER = 1173
PARTS_NGP2_STRIKE4_LINER = 1174

NGP_PARTS_ID_TO_NAME = {
    PARTS_NGP1_LIGHT_FRAME: "Workshop Union Lightweight Frame +1",
    PARTS_NGP1_STRENGTHENING_FRAME: "Workshop Union Strengthening Frame +1",
    PARTS_NGP1_HEAVY_FRAME: "Arch Heavyweight Frame +1",
    PARTS_NGP1_EXTERAHEAVY_FRAME: "Arch Extra Heavyweight Frame +1",
    PARTS_NGP1_150_FRAME: "LADA F150 Frame +1",
    PARTS_NGP1_250_FRAME: "LADA F250 Frame +1",
    PARTS_NGP1_350_FRAME: "LADA F350 Frame +1",
    PARTS_NGP2_LIGHT_FRAME: "Workshop Union Lightweight Frame +2",
    PARTS_NGP2_STRENGTHENING_FRAME: "Workshop Union Strengthening Frame +2",
    PARTS_NGP2_HEAVY_FRAME: "Arch Heavyweight Frame +2",
    PARTS_NGP2_EXTERAHEAVY_FRAME: "Arch Extra Heavyweight Frame +2",
    PARTS_NGP2_150_FRAME: "LADA F150 Frame +2",
    PARTS_NGP2_250_FRAME: "LADA F250 Frame +2",
    PARTS_NGP2_350_FRAME: "LADA F350 Frame +2",
    PARTS_NGP1_BREAK1_CART: "Belford Break Cartridge +1",
    PARTS_NGP1_DISRUPTION1_CART: "Belford Disruption Cartridge +1",
    PARTS_NGP1_SHOCK1_CART: "Belford Shock Cartridge +1",
    PARTS_NGP1_BREAK2_CART: "Arch Break Cartridge +1",
    PARTS_NGP1_DISRUPTION2_CART: "Arch Disruption Cartridge +1",
    PARTS_NGP1_SHOCK2_CART: "Arch Shock Cartridge +1",
    PARTS_NGP1_BREAK3_CART: "LADA Break Cartridge +1",
    PARTS_NGP1_DISRUPTION3_CART: "LADA Disruption Cartridge +1",
    PARTS_NGP1_SHOCK3_CART: "LADA Shock Cartridge +1",
    PARTS_NGP2_BREAK1_CART: "Belford Break Cartridge +2",
    PARTS_NGP2_DISRUPTION1_CART: "Belford Disruption Cartridge +2",
    PARTS_NGP2_SHOCK1_CART: "Belford Shock Cartridge +2",
    PARTS_NGP2_BREAK2_CART: "Arch Break Cartridge +2",
    PARTS_NGP2_DISRUPTION2_CART: "Arch Disruption Cartridge +2",
    PARTS_NGP2_SHOCK2_CART: "Arch Shock Cartridge +2",
    PARTS_NGP2_BREAK3_CART: "LADA Break Cartridge +2",
    PARTS_NGP2_DISRUPTION3_CART: "LADA Disruption Cartridge +2",
    PARTS_NGP2_SHOCK3_CART: "LADA Shock Cartridge +2",
    PARTS_NGP1_CORROSION1_CONV: "Workshop Union Standard Corrosion Resistance Converter +1",
    PARTS_NGP1_INSULATION1_CONV: "Workshop Union Standard Insulation Converter +1",
    PARTS_NGP1_RADIATION1_CONV: "Workshop Union Standard Radiation Converter +1",
    PARTS_NGP1_CORROSION2_CONV: "Belford Superior Corrosion Resistance Converter +1",
    PARTS_NGP1_INSULATION2_CONV: "Belford Superior Insulation Converter +1",
    PARTS_NGP1_RADIATION2_CONV: "Belford Superior Radiation Converter +1",
    PARTS_NGP1_CORROSION3_CONV: "LADA Large Capacity Corrosion Resistance Converter +1",
    PARTS_NGP1_INSULATION3_CONV: "LADA Large Capacity Insulation Converter +1",
    PARTS_NGP1_RADIATION3_CONV: "LADA Large Capacity Radiation Converter +1",
    PARTS_NGP2_CORROSION1_CONV: "Workshop Union Standard Corrosion Resistance Converter +2",
    PARTS_NGP2_INSULATION1_CONV: "Workshop Union Standard Insulation Converter +2",
    PARTS_NGP2_RADIATION1_CONV: "Workshop Union Standard Radiation Converter +2",
    PARTS_NGP2_CORROSION2_CONV: "Belford Superior Corrosion Resistance Converter +2",
    PARTS_NGP2_INSULATION2_CONV: "Belford Superior Insulation Converter +2",
    PARTS_NGP2_RADIATION2_CONV: "Belford Superior Radiation Converter +2",
    PARTS_NGP2_CORROSION3_CONV: "LADA Large Capacity Corrosion Resistance Converter +2",
    PARTS_NGP2_INSULATION3_CONV: "LADA Large Capacity Insulation Converter +2",
    PARTS_NGP2_RADIATION3_CONV: "LADA Large Capacity Radiation Converter +2",
    PARTS_NGP1_SLASH1_LINER: "Workshop Union Fiber-Reinforced Liner +1",
    PARTS_NGP1_PIERCE1_LINER: "Workshop Union Multi-Layer Liner +1",
    PARTS_NGP1_STRIKE1_LINER: "Workshop Union Spaced Armor Liner +1",
    PARTS_NGP1_SLASH2_LINER: "Belford Fiber-Reinforced Liner +1",
    PARTS_NGP1_PIERCE2_LINER: "Belford Multi-Layer Liner +1",
    PARTS_NGP1_STRIKE2_LINER: "Belford Spaced Armor Liner +1",
    PARTS_NGP1_SLASH3_LINER: "Arch Fiber-Reinforced Liner +1",
    PARTS_NGP1_PIERCE3_LINER: "Arch Multi-Layer Liner +1",
    PARTS_NGP1_STRIKE3_LINER: "Arch Spaced Armor Liner +1",
    PARTS_NGP1_SLASH4_LINER: "LADA Fiber-Reinforced Liner +1",
    PARTS_NGP1_PIERCE4_LINER: "LADA Multi-Layer Liner +1",
    PARTS_NGP1_STRIKE4_LINER: "LADA Spaced Armor Liner +1",
    PARTS_NGP2_SLASH1_LINER: "Workshop Union Fiber-Reinforced Liner +2",
    PARTS_NGP2_PIERCE1_LINER: "Workshop Union Multi-Layer Liner +2",
    PARTS_NGP2_STRIKE1_LINER: "Workshop Union Spaced Armor Liner +2",
    PARTS_NGP2_SLASH2_LINER: "Belford Fiber-Reinforced Liner +2",
    PARTS_NGP2_PIERCE2_LINER: "Belford Multi-Layer Liner +2",
    PARTS_NGP2_STRIKE2_LINER: "Belford Spaced Armor Liner +2",
    PARTS_NGP2_SLASH3_LINER: "Arch Fiber-Reinforced Liner +2",
    PARTS_NGP2_PIERCE3_LINER: "Arch Multi-Layer Liner +2",
    PARTS_NGP2_STRIKE3_LINER: "Arch Spaced Armor Liner +2",
    PARTS_NGP2_SLASH4_LINER: "LADA Fiber-Reinforced Liner +2",
    PARTS_NGP2_PIERCE4_LINER: "LADA Multi-Layer Liner +2",
    PARTS_NGP2_STRIKE4_LINER: "LADA Spaced Armor Liner +2"
}
ALL_NGP_PARTS_MATERIALS = list(NGP_PARTS_ID_TO_NAME.keys())
