# Combined Weapons
WPN_WINTERY_RAPIER = 601
WPN_TYRANT_MURDERERS_DAGGER = 602
WPN_SPEAR_OF_HONOR = 603
WPN_SALAMANDER_DAGGER = 604
WPN_PUPPET_SABER = 605
WPN_PISTOL_ROCK_DRILL = 606
WPN_MILITARY_SHOVEL = 607
WPN_MASTER_CHEF_KNIFE = 608
WPN_LIVE_PUPPET_AXE = 609
WPN_KRAT_POLICE_BATON = 610
WPN_GREATSWORD_OF_FATE = 611
WPN_FIRE_AXE = 612
WPN_EXPLOADING_PICKAXE = 613
WPN_ELECTRIC_COILSTICK = 614
WPN_DANCERS_CURVED_SWORD = 615
WPN_CURSED_KNIGHT_HALBRED = 616
WPN_COIL_MJOLNIR = 617
WPN_CLOCKSWORD = 618
WPN_CITY_LONGSPEAR = 619
WPN_CIRCULAR_ELECTRIC_CHAINSAW = 620
WPN_CARCASS_CRYSTAL_AXE = 621
WPN_BRAMBLE_CURVED_SWORD = 622
WPN_BOOSTER_GLAIVE = 623
WPN_BONECUTTING_SAW = 624
WPN_BLINDMAN_DOUBLESIDED_SPEAR = 625
WPN_BLACK_STEEL_CUTTER = 626
WPN_BIG_PIPE_WRENCH = 627
WPN_ACIDIC_CRYSTAL_CURVED_SWORD = 628
WPN_ACIDIC_CRYSTAL_SPEAR = 629
WPN_UROBOROSS_EYE = 630
WPN_TWO_DRAGONS_SWORD = 631
WPN_TRIDENT_OF_THE_COVENENT = 632
WPN_SEVENCOIL_SPRING_SWORD = 633
WPN_PUPPET_RIPPER = 634
WPN_PROOF_OF_HUMANITY = 635
WPN_NOBLESSE_OBLIGE = 636
WPN_HOLY_SWORD_OF_THE_ARK = 637
WPN_GOLDEN_LIE = 638
WPN_FROZEN_FEAST = 639
WPN_ETIQUETTE = 640
WPN_DRAGON_GLAIVE = 641

NORMAL_WPN_ID_TO_NAME = {
    WPN_WINTERY_RAPIER: "Wintry Rapier",
    WPN_TYRANT_MURDERERS_DAGGER: "Tyrant Murderer's Dagger",
    WPN_SPEAR_OF_HONOR: "Spear of Honor",
    WPN_SALAMANDER_DAGGER: "Salamander Dagger",
    WPN_PUPPET_SABER: "Puppet's Saber",
    WPN_PISTOL_ROCK_DRILL: "Pistol Rock Drill",
    WPN_MILITARY_SHOVEL: "Military Shovel",
    WPN_MASTER_CHEF_KNIFE: "Master Chef's Knife",
    WPN_LIVE_PUPPET_AXE: "Live Puppet's Axe",
    WPN_KRAT_POLICE_BATON: "Krat Police Baton",
    WPN_GREATSWORD_OF_FATE: "Greatsword of Fate",
    WPN_FIRE_AXE: "Fire Axe",
    WPN_EXPLOADING_PICKAXE: "Exploding Pickaxe",
    WPN_ELECTRIC_COILSTICK: "Electric Coil Stick",
    WPN_DANCERS_CURVED_SWORD: "Dancer's Curved Sword",
    WPN_CURSED_KNIGHT_HALBRED: "Cursed Knight's Halberd",
    WPN_COIL_MJOLNIR: "Coil Mjolnir",
    WPN_CLOCKSWORD: "Clock Sword",
    WPN_CITY_LONGSPEAR: "City Longspear",
    WPN_CIRCULAR_ELECTRIC_CHAINSAW: "Circular Electric Chainsaw",
    WPN_CARCASS_CRYSTAL_AXE: "Carcass Crystal Axe",
    WPN_BRAMBLE_CURVED_SWORD: "Bramble Curved Sword ",
    WPN_BOOSTER_GLAIVE: "Booster Glaive",
    WPN_BONECUTTING_SAW: "Bone-Cutting Saw",
    WPN_BLINDMAN_DOUBLESIDED_SPEAR: "Blind Man's Double-Sided Spear",
    WPN_BLACK_STEEL_CUTTER: "Black Steel Cutter",
    WPN_BIG_PIPE_WRENCH: "Big Pipe Wrench",
    WPN_ACIDIC_CRYSTAL_CURVED_SWORD: "Acidic Great Curved Sword",
    WPN_ACIDIC_CRYSTAL_SPEAR: "Acidic Crystal Spear",
}
ALL_NORMAL_WPN = list(NORMAL_WPN_ID_TO_NAME.keys())

SPECIAL_WPN_ID_TO_NAME = {
    WPN_UROBOROSS_EYE: "Uroboros’s Eye",
    WPN_TWO_DRAGONS_SWORD: "Two Dragons Sword",
    WPN_TRIDENT_OF_THE_COVENENT: "Trident Of The Covenent",
    WPN_SEVENCOIL_SPRING_SWORD: "Seven-Coil Spring Sword",
    WPN_PUPPET_RIPPER: "Puppet Ripper",
    WPN_PROOF_OF_HUMANITY: "Proof Of Humanity",
    WPN_NOBLESSE_OBLIGE: "Noblesse Oblige",
    WPN_HOLY_SWORD_OF_THE_ARK: "Holy Sword Of The Ark",
    WPN_GOLDEN_LIE: "Golden Lie",
    WPN_FROZEN_FEAST: "Frozen Feast",
    WPN_ETIQUETTE: "Etiquette",
    WPN_DRAGON_GLAIVE: "Azure Dragon Crescent Glaive"
}

ALL_SPECIAL_WPN = list(SPECIAL_WPN_ID_TO_NAME.keys())

# Handles
HND_WINTERY_RAPIER = 701
HND_TYRANT_MURDERERS_DAGGER = 702
HND_SPEAR_OF_HONOR = 703
HND_SALAMANDER_DAGGER = 704
HND_PUPPET_SABER = 705
HND_PISTOL_ROCK_DRILL = 706
HND_MILITARY_SHOVEL = 707
HND_MASTER_CHEF_KNIFE = 708
HND_LIVE_PUPPET_AXE = 709
HND_KRAT_POLICE_BATON = 710
HND_GREATSWORD_OF_FATE = 711
HND_FIRE_AXE = 712
HND_EXPLOADING_PICKAXE = 713
HND_ELECTRIC_COILSTICK = 714
HND_DANCERS_CURVED_SWORD = 715
HND_CURSED_KNIGHT_HALBRED = 716
HND_COIL_MJOLNIR = 717
HND_CLOCKSWORD = 718
HND_CITY_LONGSPEAR = 719
HND_CIRCULAR_ELECTRIC_CHAINSAW = 720
HND_CARCASS_CRYSTAL_AXE = 721
HND_BRAMBLE_CURVED_SWORD = 722
HND_BOOSTER_GLAIVE = 723
HND_BONECUTTING_SAW = 724
HND_BLINDMAN_DOUBLESIDED_SPEAR = 725
HND_BLACK_STEEL_CUTTER = 726
HND_BIG_PIPE_WRENCH = 727
HND_ACIDIC_CRYSTAL_CURVED_SWORD = 728
HND_ACIDIC_CRYSTAL_SPEAR = 729
HND_UROBOROSS_EYE = 730
HND_TWO_DRAGONS_SWORD = 731
HND_TRIDENT_OF_THE_COVENENT = 732
HND_SEVENCOIL_SPRING_SWORD = 733
HND_PUPPET_RIPPER = 734
HND_PROOF_OF_HUMANITY = 735
HND_NOBLESSE_OBLIGE = 736
HND_HOLY_SWORD_OF_THE_ARK = 737
HND_GOLDEN_LIE = 738
HND_FROZEN_FEAST = 739
HND_ETIQUETTE = 740
HND_DRAGON_GLAIVE = 741

HND_ID_TO_NAME = {
    HND_WINTERY_RAPIER: "Wintry Rapier's Handle",
    HND_TYRANT_MURDERERS_DAGGER: "Tyrant Murderer's Dagger Handle",
    HND_SPEAR_OF_HONOR: "Spear of Honor Handle",
    HND_SALAMANDER_DAGGER: "Salamander Dagger Handle",
    HND_PUPPET_SABER: "Puppet's Saber Handle",
    HND_PISTOL_ROCK_DRILL: "Pistol Rock Drill Handle",
    HND_MILITARY_SHOVEL: "Military Shovel Handle",
    HND_MASTER_CHEF_KNIFE: "Master Chef's Knife Handle",
    HND_LIVE_PUPPET_AXE: "Live Puppet's Axe Handle",
    HND_KRAT_POLICE_BATON: "Krat Police Baton Handle",
    HND_GREATSWORD_OF_FATE: "Greatsword of Fate Handle",
    HND_FIRE_AXE: "Fire Axe Handle",
    HND_EXPLOADING_PICKAXE: "Exploding Pickaxe Handle",
    HND_ELECTRIC_COILSTICK: "Electric Coil Stick Handle",
    HND_DANCERS_CURVED_SWORD: "Dancer's Curved Sword Handle",
    HND_CURSED_KNIGHT_HALBRED: "Cursed Knight's Halberd Handle",
    HND_COIL_MJOLNIR: "Coil Mjolnir Handle",
    HND_CLOCKSWORD: "Clock Sword Handle",
    HND_CITY_LONGSPEAR: "City Longspear Handle",
    HND_CIRCULAR_ELECTRIC_CHAINSAW: "Circular Electric Chainsaw Handle",
    HND_CARCASS_CRYSTAL_AXE: "Carcass Crystal Axe Handle",
    HND_BRAMBLE_CURVED_SWORD: "Bramble Curved Sword Handle",
    HND_BOOSTER_GLAIVE: "Booster Glaive Handle",
    HND_BONECUTTING_SAW: "Bone-Cutting Handle",
    HND_BLINDMAN_DOUBLESIDED_SPEAR: "Blind Man's Double-Sided Spear Handle",
    HND_BLACK_STEEL_CUTTER: "Black Steel Cutter Handle",
    HND_BIG_PIPE_WRENCH: "Big Pipe Wrench Handle",
    HND_ACIDIC_CRYSTAL_CURVED_SWORD: "Acidic Great Curved Sword Handle",
    HND_ACIDIC_CRYSTAL_SPEAR: "Acidic Crystal Spear Handle",
    HND_UROBOROSS_EYE: "Uroboros’s Eye Handle",
    HND_TWO_DRAGONS_SWORD: "Two Dragons Sword Handle",
    HND_TRIDENT_OF_THE_COVENENT: "Trident Of The Covenent Handle",
    HND_SEVENCOIL_SPRING_SWORD: "Seven-Coil Spring Sword Handle",
    HND_PUPPET_RIPPER: "Puppet Ripper Handle",
    HND_PROOF_OF_HUMANITY: "Proof Of Humanity Handle",
    HND_NOBLESSE_OBLIGE: "Noblesse Oblige",
    HND_HOLY_SWORD_OF_THE_ARK: "Holy Sword Of The Ark",
    HND_GOLDEN_LIE: "Golden Lie Handle",
    HND_FROZEN_FEAST: "Frozen Feast Handel",
    HND_ETIQUETTE: "Etiquette",
    HND_DRAGON_GLAIVE: "Azure Dragon Crescent Glaive Handle",
}
ALL_HND = list(HND_ID_TO_NAME.keys())

# blades
BLD_WINTERY_RAPIER = 801
BLD_TYRANT_MURDERERS_DAGGER = 802
BLD_SPEAR_OF_HONOR = 803
BLD_SALAMANDER_DAGGER = 804
BLD_PUPPET_SABER = 805
BLD_PISTOL_ROCK_DRILL = 806
BLD_MILITARY_SHOVEL = 807
BLD_MASTER_CHEF_KNIFE = 808
BLD_LIVE_PUPPET_AXE = 809
BLD_KRAT_POLICE_BATON = 810
BLD_GREATSWORD_OF_FATE = 811
BLD_FIRE_AXE = 812
BLD_EXPLOADING_PICKAXE = 813
BLD_ELECTRIC_COILSTICK = 814
BLD_DANCERS_CURVED_SWORD = 815
BLD_CURSED_KNIGHT_HALBRED = 816
BLD_COIL_MJOLNIR = 817
BLD_CLOCKSWORD = 818
BLD_CITY_LONGSPEAR = 819
BLD_CIRCULAR_ELECTRIC_CHAINSAW = 820
BLD_CARCASS_CRYSTAL_AXE = 821
BLD_BRAMBLE_CURVED_SWORD = 822
BLD_BOOSTER_GLAIVE = 823
BLD_BONECUTTING_SAW = 824
BLD_BLINDMAN_DOUBLESIDED_SPEAR = 825
BLD_BLACK_STEEL_CUTTER = 826
BLD_BIG_PIPE_WRENCH = 827
BLD_ACIDIC_CRYSTAL_CURVED_SWORD = 828
BLD_ACIDIC_CRYSTAL_SPEAR = 829
BLD_UROBOROSS_EYE = 830
BLD_TWO_DRAGONS_SWORD = 831
BLD_TRIDENT_OF_THE_COVENENT = 832
BLD_SEVENCOIL_SPRING_SWORD = 833
BLD_PUPPET_RIPPER = 834
BLD_PROOF_OF_HUMANITY = 835
BLD_NOBLESSE_OBLIGE = 836
BLD_HOLY_SWORD_OF_THE_ARK = 837
BLD_GOLDEN_LIE = 838
BLD_FROZEN_FEAST = 839
BLD_ETIQUETTE = 840
BLD_DRAGON_GLAIVE = 841

BLD_ID_TO_NAME = {
    BLD_WINTERY_RAPIER: "Wintry Rapier's Blade",
    BLD_TYRANT_MURDERERS_DAGGER: "Tyrant Murderer's Dagger Blade",
    BLD_SPEAR_OF_HONOR: "Spear of Honor Blade",
    BLD_SALAMANDER_DAGGER: "Salamander Dagger Blade",
    BLD_PUPPET_SABER: "Puppet's Saber Blade",
    BLD_PISTOL_ROCK_DRILL: "Pistol Rock Drill Blade",
    BLD_MILITARY_SHOVEL: "Military Shovel Blade",
    BLD_MASTER_CHEF_KNIFE: "Master Chef's Knife Blade",
    BLD_LIVE_PUPPET_AXE: "Live Puppet's Axe Blade",
    BLD_KRAT_POLICE_BATON: "Krat Police Baton Blade",
    BLD_GREATSWORD_OF_FATE: "Greatsword of Fate Blade",
    BLD_FIRE_AXE: "Fire Axe Blade",
    BLD_EXPLOADING_PICKAXE: "Exploding Pickaxe Blade",
    BLD_ELECTRIC_COILSTICK: "Electric Coil Stick Blade",
    BLD_DANCERS_CURVED_SWORD: "Dancer's Curved Sword Blade",
    BLD_CURSED_KNIGHT_HALBRED: "Cursed Knight's Halberd Blade",
    BLD_COIL_MJOLNIR: "Coil Mjolnir Blade",
    BLD_CLOCKSWORD: "Clock Sword Blade",
    BLD_CITY_LONGSPEAR: "City Longspear Blade",
    BLD_CIRCULAR_ELECTRIC_CHAINSAW: "Circular Electric Chainsaw Blade",
    BLD_CARCASS_CRYSTAL_AXE: "Carcass Crystal Axe Blade",
    BLD_BRAMBLE_CURVED_SWORD: "Bramble Curved Sword Blade",
    BLD_BOOSTER_GLAIVE: "Booster Glaive Blade",
    BLD_BONECUTTING_SAW: "Bone-Cutting Saw Blade",
    BLD_BLINDMAN_DOUBLESIDED_SPEAR: "Blind Man's Double-Sided Spear Blade",
    BLD_BLACK_STEEL_CUTTER: "Black Steel Cutter Blade",
    BLD_BIG_PIPE_WRENCH: "Big Pipe Wrench Blade",
    BLD_ACIDIC_CRYSTAL_CURVED_SWORD: "Acidic Great Curved Sword Blade",
    BLD_ACIDIC_CRYSTAL_SPEAR: "Acidic Crystal Spear Blade",
    BLD_UROBOROSS_EYE: "Uroboros’s Eye Blade",
    BLD_TWO_DRAGONS_SWORD: " Two Dragons Sword Blade",
    BLD_TRIDENT_OF_THE_COVENENT: "Trident Of The Covenent Blade",
    BLD_SEVENCOIL_SPRING_SWORD: "Seven-Coil Spring Sword Blade",
    BLD_PUPPET_RIPPER: "Puppet Ripper Blade",
    BLD_PROOF_OF_HUMANITY: "Proof Of Humanity Blade",
    BLD_NOBLESSE_OBLIGE: "Noblesse Oblige Blade",
    BLD_HOLY_SWORD_OF_THE_ARK: "Holy Sword Of The Ark Blade",
    BLD_GOLDEN_LIE: "Golden Lie Blade",
    BLD_FROZEN_FEAST: "Blade",
    BLD_ETIQUETTE: "Frozen Feast Blade",
    BLD_DRAGON_GLAIVE: "Azure Dragon Crescent Glaive Blade"
}
ALL_BLD = list(BLD_ID_TO_NAME.keys())
